version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: "foreman start -f Procfile"
    volumes:
      - .:/usr/src/app/
      - bundle:/usr/local/bundle/
    ports:
      - 3000:3000
    environment:
      # Environment that the system expects
      - RACK_ENV=development
      - HOSTNAME=${HOSTNAME}
      - MAX_THREADS=10
      # For developer use
      - CUCUMBER_PUBLISH_TOKEN=a9c7a1e2-f0d6-49fe-8d80-f231f4c44335
volumes:
  bundle:
