default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: data/database.sqlite3

test:
  <<: *default
  database: data/test.sqlite3

staging:
  <<: *default
  database: data/database.sqlite3

production:
  <<: *default
  database: data/database.sqlite3
