name: Run tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Set up database 
      run: bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:test:prepare
    - name: Run tests
      run: bundle exec rake:spec
